config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  #管理者側ルーティング
  namespace :admin do
    root to: "orders#index" #管理者側TOPページ
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  #顧客側ルーティング
  scope module: :public do

  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post 'confirm'
    end
    collection do
      get 'thanks'
    end
  end

  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  resource "customers", path: 'customers/my_page', only: [:edit, :show, :update]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  root to: "homes#top"
  get "about" => "homes#about", as: "about"
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}, numericality: true #numericality:属性に数値のみが使えるバリデーション
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 11, minimum: 10}, numericality: true

  # orderモデルで使用します。〒OOO-OOO 住所 宛名
  def address_display
    '〒' + post_code + ' ' + address + ' ' + last_name + first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :post_code, :phone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col-12 mt-4">
        <h3><strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</strong></h3>
      </div>
    </div>


      <div class="row mt-5">
      <%= form_with model: @customer, url: admin_customer_path do |f| %>
      <div class="form-group row">
        <div class="col-4"><strong>会員ID</strong></div>
        <div class="col-8"><%= @customer.id %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>氏名</strong></div>
        <div class="col-4"><%= f.text_field :last_name, autofocus: true, class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name, class: "form-control" %></div>
      </div>

       <div class="form-group row">
        <div class="col-4"><strong>フリガナ</strong></div>
        <div class="col-4"><%= f.text_field :last_name_kana, class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name_kana, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>郵便番号</strong></div>
        <div class="col-4"><%= f.text_field :post_code, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>住所</strong></div>
        <div class="col-8"><%= f.text_field :address, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>電話番号</strong></div>
        <div class="col-4"><%= f.text_field :phone_number, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>メールアドレス</strong></div>
        <div class="col-8"><%= f.email_field :email, class: "form-control" %></div>
      </div>

      <div class="form-group row">
        <div class="col-4"><strong>会員ステータス</strong></div>
        <div class="col-8">
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, "退会" %>
        </div>
      </div>

      <div class="row">
        <div class="col-4"></div>
        <div class="col-8"><%= f.submit "編集内容を保存", class: 'btn btn-success' %></div>
      </dvi>

    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
  <div class='container px-5 px-sm-0'>
    <table class='table table-hover table-inverse'>
     <thead>
       <tr>
         <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
         <th colspan="4"></th>
       </tr>
     </thead>
    <% @customers.each do |customer| %>
       <tbody>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <%= customer.is_deleted? ? "退会" : "有効" %>
            </td>
            <% end %>
          </tr>
       </tbody>
    </table>

    <%= paginate @customers %>

  </div>

app/views/admin/customers/show.html.erb
<div class="container">
  
  <div class="row mt-5 mb-4">
    <div class="col-lg-4">
      <h3 class="table-active"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-7">
      <table class="admin_show_customer">
        <tr class="active">
          <th>顧客ID</th>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>

        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>

        <tr>
          <th>郵便番号</th>
          <td><%= @customer.post_code.to_s.insert(3, "-") %></td>
        </tr>

        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <th>電話番号</th>
          <td><%= @customer.phone_number.to_s.insert(3, "-").insert(8, "-") %></td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>

        <tr>
          <th>会員ステータス</th>
          <td><%= @customer.is_deleted? ? "退会" : "有効" %></td>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-2 my-auto">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-info" %>
    </div>
    <div class="col-log-2 my-auto">
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-info" %>
    </div>
  </div>
  
</div>