config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  #管理者側ルーティング
  namespace :admin do
    root to: "orders#index" #管理者側TOPページ
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  #顧客側ルーティング
  scope module: :public do

  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :create, :index, :show] do
    collection do
      post 'confirm'
    end
    collection do
      get 'thanks'
    end
  end

  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  resource "customers", path: 'customers/my_page', only: [:edit, :show, :update]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  root to: "homes#top"
  get "about" => "homes#about", as: "about"
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: { maximum: 7, minimun: 7 },numericality: true
  validates :address, presence: true
  validates :name, presence: true




  # orderモデルで使用します。〒OOO-OOO 住所 宛名
  def address_display
  '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :quantity, presence: true


  # 小計を求めるメソッド
  def subtotal
    item.add_tax_price * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}, numericality: true #numericality:属性に数値のみが使えるバリデーション
  validates :address, presence: true
  validates :phone_number, presence: true, length: {maximum: 11, minimum: 10}, numericality: true

  # orderモデルで使用します。〒OOO-OOO 住所 宛名
  def address_display
    '〒' + post_code + ' ' + address + ' ' + last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, uniqueness: true, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items
  has_many :order_details

  belongs_to :genre

  has_one_attached :image

  validates :is_active, inclusion: { in: [true, false] }
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true


  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details

  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, confirm_payment: 1, production: 2, send_ready: 3, send_complete: 4 }



  def add_tax_price
    (self.price * 1.1).round
  end

    # 小計を求めるメソッド
  def subtotal
    item.add_tax_price * quantity
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: true #←在庫数20の制限かけたいが、不明
  validates :price, numericality: true
  validates :production_status, presence: true

  enum production_status: { pending: 0, waiting: 1, working: 2, completed: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path(@genre)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genres)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # @item.genre_id = genre.id
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
     if @order.status == "confirm_payment"#入金確認
      @order_details.update_all(production_status: 1)
     end
      redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-xxl mt-5" style="background-color: #d6e9ca;">
    <div class="row">
      <div class="mx-auto">
        <div class="d-flex justify-content-around px-5  mt-3 mb-1">
          <i class="fab fa-brands fa-twitter-square icon_white"></i>
          <i class="fab fa-brands fa-instagram-square icon_white"></i>
          <i class="fab fa-brands fa-facebook-square icon_white"></i>
        </div>
        <p class="icon_green mb-1">Everyone level up after 20 days</p>
      </div>
    </div>
  </div>

  <style>
    .icon_white {
      color: #f8f9fa;

    }
    .icon_green {
      color: #336666;
      font-size: 12px;
  </style>

</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #d6e9ca;">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag("logo_long.png") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

      <nav class="navbar navbar-light">
      <form class="container-fluid justify-content-start">

        <% if customer_signed_in? %>
         <p class="active"><i class="fas fa-user-circle"></i>ようこそ、<%= current_customer.last_name %>さん！！</p>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to customers_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-user"></i>　マイページ
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to items_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-cheese"></i>　商品一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%=  link_to cart_items_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-cart-plus"></i>　カート
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i>　ログアウト
            <% end %>
            </button>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to admin_items_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-cheese"></i>　商品一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to admin_customers_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-users"></i>　会員一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%=  link_to admin_orders_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-clock"></i>　注文履歴一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to admin_genres_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-tags"></i>　ジャンル一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i>　ログアウト
            <% end %>
            </button>
          </li>
        <% else %>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to about_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-store"></i> About
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to items_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-solid fa-cheese"></i> 商品一覧
            <% end %>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to new_customer_registration_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </button>
          </li>
          <li>
            <button type="button" class="btn btn-sm btn-outline-light ml-2">
            <%= link_to new_customer_session_path ,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
            </button>
          </li>
        <% end %>
        </form>
        </nav>
        </ul>
      </div>
    </div>
  <div class="text-right">
    <input type="text">
    <i class="fas fa-search"></i>
  </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaguya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>